- hosts: localhost
  become_user: root
  vars_files: vars.yml
  tasks:
    - name: Start uftp
      command: uftp -P 230.5.5.1 -L /var/log/uftp/log -R 100000000 -z -m 10 -u 1044 -I eth1 /srv/uftp/vm/w11.qcow2 /srv/uftp/vm/Suse.qcow>

#    - name: start uftpd
#      command: sudo ansible-playbook uftpd.yml
